### ISSUE TITLE
Recipes to use attributes

### ISSUE THREAD

**Issue by floored1585** [CumulusNetworks/cumulus-linux-chef-modules#21]
Is there any interest at Cumulus in having this cookbook include recipes as well as providers?

I'm doing some work on a cookbook that consists of recipes for utilizing your LWRPs (basically taking node attributes and feeding them into the providers).  It seems like that would make more sense to be part of this cookbook, so if that would be something you'd consider within the scope of this cookbook I'd like to submit PRs to bring in that functionality.

**Comment by 8bitdad** [comment]
We will never say no to this kind of assistance. We would love to see what you have in mind.

**Comment by LeslieCarr** [comment]
So, I'm wondering if another repository "chef recipes" might be even better? I'm not as familiar with the chef community and whether or not recipes are desired within modules

**Comment by floored1585** [comment]
We decided to roll our own thing for this, it's located [here](https://github.com/dreamhost/cumulus-switch) if anyone else is interested in the functionality!  Thanks for the feedback about the idea.
