### ISSUE TITLE
network description & quotes

### ISSUE THREAD

**Issue by floored1585** [CumulusNetworks/cumulus-linux-chef-modules#23]
Heya,

Right now if you use alias_name in any of the providers, it puts quotes around the alias, which are escaped and passed through to SNMP by snmpifAlias_pp.py, resulting in every interface description having quotes around it when SNMP polls are run.

In my testing I haven't seen any negative effects with simply removing the quotes around the alias, so that:

alias "mgmt interface"
becomes:
alias mgmt interface

For the second line, SNMP pollers don't get quotes around everything, and they still get the whole alias.

I suppose the other option here would be to have /usr/share/snmp/snmpifAlias_pp.py strip out the quotes, but probably better to just not add them at all if they're not necessary.

Is there a reason for wrapping the alias in quotes, or can that be changed in a PR?

**Comment by skamithi** [comment]
It can be changed in a PR. Thanks for finding the problem.
